name: Download and Upload Clonezilla
#clonezilla-live-3.1.3-16-i686.iso
on:
  repository_dispatch:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  
        # Enable LFS support

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install

    - name: Download Clonezilla ISO
      run: wget -O clonezilla-live.iso "https://master.dl.sourceforge.net/project/clonezilla/clonezilla_live_stable/3.1.3-16/clonezilla-live-3.1.3-16-i686.iso?viasf=1"

    - name: Create download directory
      run: mkdir -p download

    - name: Move ISO to download directory
      run: mv clonezilla-live.iso download/

    - name: Track ISO with Git LFS
      run: |
        git lfs track "download/clonezilla-live.iso"
        git add .gitattributes

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add download/clonezilla-live.iso
        git commit -m "Add Clonezilla ISO"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
